name: Feature request
description: Request a new feature for the dashboard/workflow
title: "[Feature]: "
labels: ["type/feature", "status/backlog"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / goal
      description: What are you trying to accomplish?
      placeholder: "As a user, I want..."
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope / requirements
      description: Bullet points are fine.
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know it's done?
      placeholder: "- [ ] ..."
    validations:
      required: false
